spring:
  security:    oauth2:      client:              registration:          auth0:
            client-name: auth0.com
            client-id: 05pyqADP35YvmZms9PWPLzCOaSP4elrF
            client-secret: WhKr_qtaeWtCWhuqFa5U0CQyPPgtmMhPOvgsEFDqHr3gkd525SeQi0FRcMcjb342
            scope:            - openid
            - profile
            - email
        provider:          auth0:
            issuer-uri: https://dev-jkd6ttlt.us.auth0.com/
            #authorization-uri: 
            #token-uri: 
            #jwk-set-uri: 
            #user-info-uri: 
          
logging:
  level:
    root: info
    #org.springframework: debug
    #org.springframework.security.oauth2: debug